CREATE TABLE jobs (
	job_id TEXT NOT NULL PRIMARY KEY,
	model SMALLINT NOT NULL,
	original_filename TEXT NOT NULL,
	state INT NOT NULL DEFAULT 0,
	added TIMESTAMP NOT NULL DEFAULT NOW(),
	changed TIMESTAMP NOT NULL DEFAULT NOW(),
	CHECK(model IN(1,2))
);